apiVersion: apps/v1
kind: Deployment
metadata:
  name: clusterapi-manager-controllers
  namespace: {{ .TargetNamespace }}
  labels:
    api: clusterapi
    k8s-app: controller
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
  selector:
    matchLabels:
      api: clusterapi
      k8s-app: controller
  replicas: 1
  template:
    metadata:
      labels:
        api: clusterapi
        k8s-app: controller
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        key: node.alpha.kubernetes.io/notReady
        operator: Exists
      - effect: NoExecute
        key: node.alpha.kubernetes.io/unreachable
        operator: Exists
      containers:
      - name: controller-manager
        image: {{ .Controllers.Provider }}
        command:
          - "./manager"
        args:
          - --logtostderr=true
          - --v=3
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 30Mi
      - name: machine-controller
        image: {{ .Controllers.Provider }}
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        command:
          - /machine-controller-manager
        args:
          - --logtostderr=true
          - --v=3
      - name: controller-manager-deprecated
        image: {{ .Controllers.ProviderDeprecated }}
        command:
        - "./manager"
        args:
          - --logtostderr=true
          - --v=3
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 30Mi
      - name: machine-controller-deprecated
        image: {{ .Controllers.ProviderDeprecated }}
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        command:
          - /machine-controller-manager
        args:
          - --logtostderr=true
          - --v=3
      - name: nodelink-controller-deprecated
        image: quay.io/coreos/machine-api-operator:origin-v4.0-2019-01-31-041134
        command:
          - /nodelink-controller
        args:
          - --logtostderr=true
          - --v=3
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 30Mi
      - name: nodelink-controller
        image: {{ .Controllers.NodeLink }}
        command:
          - /nodelink-controller
        args:
          - --logtostderr=true
          - --v=3
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 30Mi
      - name: machine-healthcheck-deprecated
        image: quay.io/coreos/machine-api-operator:origin-v4.0-2019-01-31-041134
        command:
          - /machine-healthcheck
        args:
          - --logtostderr=true
          - --v=3
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 30Mi
      - name: machine-healthcheck
        image: {{ .Controllers.MachineHealthCheck }}
        command:
          - /machine-healthcheck
        args:
          - --logtostderr=true
          - --v=3
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 30Mi