---
apiVersion: cluster.k8s.io/v1alpha1
kind: MachineSet
metadata:
  name: worker
  namespace: {{ .TargetNamespace }}
  labels:
    sigs.k8s.io/cluster-api-cluster: {{.AWS.ClusterName}}
    sigs.k8s.io/cluster-api-machine-role: worker
    sigs.k8s.io/cluster-api-machine-type: worker
spec:
  replicas: {{.AWS.Replicas}}
  selector:
    matchLabels:
      sigs.k8s.io/cluster-api-machineset: worker
      sigs.k8s.io/cluster-api-cluster: {{.AWS.ClusterName}}
  template:
    metadata:
      labels:
        sigs.k8s.io/cluster-api-machineset: worker
        sigs.k8s.io/cluster-api-cluster: {{.AWS.ClusterName}}
        sigs.k8s.io/cluster-api-machine-role: worker
        sigs.k8s.io/cluster-api-machine-type: worker
    spec:
      providerConfig:
        value:
          apiVersion: aws.cluster.k8s.io/v1alpha1
          kind: AWSMachineProviderConfig
          {{- if .AWS.WithCreds }}
          credentialsSecret:
            name: aws-credentials-secret
          {{- end}}
          ami:
            id: {{.AWS.Image}}
            filters:
              - name: "name"
                values:
                - CoreOS-{{.AWS.ReleaseChannel}}-{{.AWS.ContainerLinuxVersion}}-*
              - name: "architecture"
                values:
                - "x86_64"
              - name: "virtualization-type"
                values:
                - "hvm"
              - name: "owner-id"
                values:
                - "595879546273"
          instanceType: m4.large
          placement:
            region: {{.AWS.Region}}
            availabilityZone: {{.AWS.AvailabilityZone}}
          subnet:
            filters:
            - name: "tag:Name"
              values:
              - "{{.AWS.ClusterName}}-worker-*"
          publicIp: true
          iamInstanceProfile:
            id: "{{.AWS.ClusterName}}-worker-profile"
          tags:
            - name: tectonicClusterID
              value: {{.AWS.ClusterID}}
          securityGroups:
            - filters:
              - name: "tag:Name"
                values:
                - "{{.AWS.ClusterName}}_worker_sg"
          userDataSecret:
            name: ignition-worker
      versions:
        kubelet: ""
        controlPlane: ""
